export const UNSAFE_EXTENSIONS = [
    '.php',
    '.exe',
    '.com',
    '.dll',
    '.pif',
    '.application',
    '.gadget',
    '.msi',
    '.jar',
    '.cmd',
    '.bat',
    '.reg',
    '.sh',
    '.py',
    '.js',
    '.jse',
    '.jsp',
    '.pdf',
    '.html',
    '.htm',
    '.hta',
    '.vb',
    '.vbs',
    '.vbe',
    '.cpl',
    '.msc',
    '.scr',
    '.sql',
    '.iso',
    '.img',
    '.dmg',
    '.ps1',
    '.ps1xml',
    '.ps2',
    '.ps2xml',
    '.psc1',
    '.psc2',
    '.msh',
    '.msh1',
    '.msh2',
    '.mshxml',
    '.msh1xml',
    '.msh2xml',
    '.scf',
    '.lnk',
    '.inf',
    '.reg',
    '.doc',
    '.docm',
    '.docx',
    '.dot',
    '.dotm',
    '.dotx',
    '.xls',
    '.xlsm',
    '.xlsx',
    '.xlt',
    '.xltm',
    '.xltx',
    '.xlam',
    '.ppt',
    '.pptm',
    '.pptx',
    '.pot',
    '.potm',
    '.potx',
    '.ppam',
    '.ppsx',
    '.ppsm',
    '.pps',
    '.ppam',
    '.sldx',
    '.sldm',
    '.ws',
];

export const MERGE_DIRECTORIES = [
    'characters',
    'chats',
    'group chats',
    'worlds',
    'groups',
    'themes',
    'backgrounds',
    'movingUI',
    'thumbnails',
    'QuickReplies',
    'instruct',
    'context',
    'sysprompt',
    'reasoning',
    'NovelAI Settings',
    'KoboldAI Settings',
    'OpenAI Settings',
    'TextGen Settings',
    'user',
    'user/images',
    'user/files',
    'user/workflows',
    'User Avatars',
    'assets',
    'extensions',
    'vectors',
    'backups',
];

export const OVERWRITE_FILES = [
    'settings.json',
    'stats.json',
    'content.log',
    'secrets.json',
];
